Web_Blog/Web_Blog/Controllers/KullaniciController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using Web_Blog.Models; 

namespace Web_Blog.Controllers
{
    public class KullaniciController : Controller
    {
        blog_Db db = new blog_Db();
        // GET: Kullanici
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Uye uye)
        {
            var login = db.Uyes.Where(u => u.Kullanici_Adi == uye.Kullanici_Adi).SingleOrDefault();
                if(login.Kullanici_Adi==uye.Kullanici_Adi &&login.Email==uye.Email&&login.Sifre==uye.Sifre)
            {
                Session["Uye_Id"] = login.Uye_Id;
                Session["Kullanici_Adi"] = login.Kullanici_Adi;
                Session["Yetki_id"] = login.Yetki_Id;
                return RedirectToAction("Hakkimizda", "Home");
            }
                else
            {
                return View("Index","Home");
            }

        }

        public ActionResult Logout()
        {
            return RedirectToAction("Index","Home");
            Session["Uye_Id"] = null;
            Session.Abandon();//Sonlandırıyoruz 
        }


        public ActionResult Yeni_Kullanici()
        {
            return View();
        }

       [HttpPost]
        public ActionResult Yeni_Kullanici(Uye uye ,HttpPostedFileBase Foto)
        {   
            if (ModelState.IsValid)
            {
                if (Foto != null)
                {
                    WebImage img = new WebImage(Foto.InputStream);
                    FileInfo Fotoinfo = new FileInfo(Foto.FileName);
                    string newfoto = Guid.NewGuid().ToString() + Fotoinfo.Extension;
                    img.Resize(150, 150);
                    img.Save("~/Uploads/KullaniciFoto/" + newfoto);
                    uye.Foto = "/Uploads/KullaniciFoto/" + newfoto;
                    uye.Yetki_Id = 2;
                    db.Uyes.Add(uye);
                    db.SaveChanges();
                    Session["uyeid"] = uye.Uye_Id;
                    Session["Kullanici_Adi"] = uye.Kullanici_Adi;
                    return RedirectToAction("Index","Home");
                }
                else
                {
                    ModelState.AddModelError("Fotograf ", "Fotograf Seciniz");
                    
                }
            }
            return View(uye);
        }
    }
}

Web_Blog/Web_Blog/Views/Kullanici/Login.cshtml
@model Web_Blog.Models.Uye

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Üye girişi</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
       
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Kullanici_Adi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kullanici_Adi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kullanici_Adi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control",@type="password" } })
                @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Giriş Yap" class="btn btn-default" />
            </div>
        </div>
    </div>
}

Web_Blog/Web_Blog/Views/Kullanici/Yeni_Kullanici.cshtml
@model Web_Blog.Models.Uye

@{
    ViewBag.Title = "Yeni_Kullanici";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Yeni Üye Kayıt</h2>

@using (Html.BeginForm("Yeni_Kullanici", "Kullanici", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Kullanici_Adi, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Kullanici_Adi, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Kullanici_Adi, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2",@type="email" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sifre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sifre, new { htmlAttributes = new { @class = "form-control", @type = "password" } })
                @Html.ValidationMessageFor(model => model.Sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdSoyad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdSoyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdSoyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="Foto" id="Foto" accept=".jpg,.png,.gif,.,JPEG,.jpeg" class="form-control" />
                @Html.ValidationMessageFor(model => model.Foto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Üye ol" class="btn btn-default" />
            </div>
        </div>
    </div>
}